### ISSUE TITLE
Permission 'action' is unknown or URL pattern is malformed.

### ISSUE THREAD

**Issue by Coru89** [warezit/Upwork-Job-Scraper#13]
![image](https://github.com/user-attachments/assets/f65ad70c-2b36-4b78-8c0f-0d182cc83030)

**Comment by warezit** [comment]
Thank you for sending this! Looks like the permission was left over from development, and is unneeded. Removed in 1.6.

**Comment by Coru89** [comment]
welcome! Thanks again. I tested out 1.7. Seems to be working. =)

**Comment by warezit** [comment]
@Coru89 

Awesome! That's great to hear!

I had some issues with 1.7, and had to roll back to 1.6 - also, after a lot of development yesterday, I got up to v1.17 and things were breaking badly. So I had to roll back again, unfortunately (just to save myself headaches).

BUT, on that note ... this extension is now in the Chrome Extension Store!! 🥳

Link here: https://chromewebstore.google.com/detail/upwork-job-scraper-+-webh/mojpfejnpifdgjjknalhghclnaifnjkg?authuser=0&hl=en

(It's version 1.6 currently, and I will be adding more feed scraping details to the JSON data passing to the webhook in the next version)

I recommend you use the Chrome Extension store version, for easy upgrades (unless you like being on the bleeding edge with Github) 😉

Please let me know if you have any other issues! Thank you again for the feedback!

**Comment by warezit** [comment]
@Coru89 

I have some exciting news, hopefully ...

v1.27 is completed now!

I just wanted to let you know specifically, since you are an early adopter :)

This has TONS of bug fixes, interface styling updates, and scrapes A TON more data from Upwork and passes the data to the webhook via JSON. It's not 100% perfect, but it's a LOT better than v1.6 or v1.7 - grabs a bunch more info.

I'm _still_ waiting on Google to approve a version I uploaded about 8 hours ago ... so, I'll upload v1.27 here, for now, if you feel like checking it out before it posted to the Google Extension store.

[upwork-job-scraper-1.27.zip](https://github.com/user-attachments/files/16857399/upwork-job-scraper-1.27.zip) (I'll remove this link after Google approves the updated version - the version on Google is still v1.6)

Give it a peek, if you want. Hope things work much better!

Cheers! 🍻

**Comment by Coru89** [comment]
Sweet! Thanks for the message. Yah the 1.7 I was on stopped working, and I jumped to 1.6 and that seems to work...but myaybe not perfectly. About to jump to the 1.27 and see how it is! Cheers!

**Comment by warezit** [comment]
Definitely in development 😉

Let me know how it goes!

I'm trying to get auto-error reporting set up right now.

**Comment by Coru89** [comment]
Of course! Appreciate the work! Thanks, you are a legend! 🔥

**Comment by warezit** [comment]
@Coru89 

Just a friendly personal update for ya 😊

I realize the previous version was not scraping the job data correctly (specifically budgets for fixed priced jobs, and some other info). I've put in a bunch more work on this, and now have much more accurate and verbose data being scraped for each job! I'm just excited about it, and had to tell someone now that it's working better lol

Anyhow - major changes coming in v1.34 (and higher) - stay tuned!

Happy Friday! 🥳
